pluginPrefix: "&f&lHooks » &r"

webhooks:
  litebans: ""
  luckperms: ""

##########################################################################
# Language
##########################################################################
lang:
  missingPermissions: "&cYou don't have the required permissions!"