name: DiscordHooks
version: 1.2.0
author: budi1200
main: si.budimir.discordHooks.DiscordHooksMain
api-version: 1.16
depends: [LiteBans, LuckPerms]
commands:
  reload:
    description: Reload plugin
    usage: /dh reload

permissions:
  discordhooks.admin.reload:
    description: Reload the plugin
    default: op